version: "3.8"

services:

  backend:
    restart: always
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: backend_container
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build

  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postgres_db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "81:80"
    container_name: nginx_container
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend: