# Generated by Django 5.0.6 on 2024-06-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('gender', models.CharField(choices=[('unknown', 'Unknown'), ('female', 'Female'), ('male', 'Male')], default='unknown', max_length=50, verbose_name='Gender')),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
                ('about', models.CharField(blank=True, max_length=100, verbose_name='About User')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'ordering': ['user'],
            },
        ),
    ]
