# Generated by Django 5.0.6 on 2024-06-05 16:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to=account.models.get_image_path, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
