# Generated by Django 5.0.6 on 2024-06-10 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Difficulties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=50, verbose_name='Difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, unique=True, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('words_number', models.IntegerField(default=0, verbose_name='Number of Words')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_article', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_category', to='blog.categories', verbose_name='Theme')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_difficulty', to='blog.difficulties', verbose_name='Difficulty')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_viewers', to='blog.article', verbose_name='Article')),
                ('viewers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Viewers')),
            ],
            options={
                'verbose_name': 'Viewers of Article',
                'ordering': ['id'],
            },
        ),
    ]
