# Generated by Django 5.0.6 on 2024-06-05 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('words_number', models.IntegerField(verbose_name='Number of Words')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('average', 'Average'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='Average', max_length=50, verbose_name='Difficulty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
