# Generated by Django 5.0.6 on 2024-06-05 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(choices=[('python', 'Python'), ('libraries', 'Libraries'), ('databases', 'Databases'), ('deploy', 'Deploy'), ('theory', 'Theory'), ('algorithms', 'Algorithms')], default='python', max_length=50, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='article',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('average', 'Average'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='average', max_length=50, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_article', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='words_number',
            field=models.IntegerField(default=0, verbose_name='Number of Words'),
        ),
        migrations.CreateModel(
            name='ArticleViewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_viewers', to='blog.article', verbose_name='Article')),
                ('viewers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Viewers')),
            ],
            options={
                'verbose_name': 'Viewers of Article',
                'ordering': ['id'],
            },
        ),
    ]
