# Generated by Django 5.0.6 on 2024-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='url_word',
            field=models.CharField(default=1, max_length=50, verbose_name='Url Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='difficulties',
            name='color',
            field=models.CharField(default=1, max_length=10, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
