# Generated by Django 5.0.6 on 2024-06-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories_url_word_difficulties_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='url_word',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
    ]
