# Generated by Django 5.0.6 on 2024-06-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_url_word_categories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficulties',
            name='color',
        ),
        migrations.AddField(
            model_name='difficulties',
            name='class_name',
            field=models.CharField(default=1, max_length=25, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
