# Generated by Django 5.0.6 on 2024-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_difficulties_color_difficulties_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulties',
            name='class_name',
            field=models.CharField(max_length=25, verbose_name='Class'),
        ),
    ]
